version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/server

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:

  BeforeInstall:
    - location: before_install.sh
      timeout: 300
#      runas: root
  
  AfterInstall:
    - location: after_install.sh
      timeout: 300
#      runas: root

  ApplicationStart:
    - location: app_start.sh
      timeout: 300
#      runas: root
