version: 0.2

phases:
  pre_build:
    commands:
        # run build script
        - npm install
       
  build:
    commands:
        # run build script
        - npm run-script build 
     
artifacts:
  type: zip
  paths:
    - '*'          
